version: '3'

services:
  # Base de données
  mongo:
    container_name: db_container
    image: mongo:latest
    ports:
     - 27017:27017
    volumes:
      - mongo_db:/data/db

  # Node
  node:
    container_name: node_container
    image: node:latest
    working_dir: /mnt/d/MDS/2023-workshop-1/
    command:
      - /bin/sh
      - -c
      - npm install & npm start
    ports:
      - 3000:3000
    volumes:
      - ./src:/mnt/d/MDS/2023-workshop-1
    links:
      - mongo

volumes:
  mongo_db:
